config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # The root path
  root "pages#home"

  # The about page path
  get "about", to: "pages#about"

  # resources :articles, only: [ :show, :index, :new, :create, :edit, :update, :destroy ]

  # REST - Representational State Transfer - mapeia os verbos HTTP (get, post, put/patch, delete) to CRUD actions
  # resources fornece rotas REST-ful para recursos Rails
  resources :articles

  # Signup
  get "signup", to: "users#new"
  resources :users, excpet: [ :new ]

  # Login
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  # Quando se tratar do campo de email para qualquer objeto, antes de salvá-lo
  # no banco de dados, ele executará o método downcase abaixo.
  before_save { self.email = email.downcase }

  # Basicamente, se um usuário for excluído, qualquer dependente associados a
  # ele, no caso os artigos, também serão destruídos.
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Quando os métodos abaixo estavam em application_helper.rb eles só poderiam ser utilizados nas views,
  # agora eles também podem ser utlizados dentro dos controllers

  # Define os métodos como métodos de ajuda para poderem ser usados nas views também
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # Usado para executar um método específico antes de qualquer ação/método da
  # classe. Se pode limitar os métodos que em que será executado antes com o
  # :only
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [ :show, :index ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  def show
    # binding.break # Utilizado para debug
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    # Resolução temporária para o uso do front-end
    @article.user = current_user

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      # A partir do Rails 7 é necessário alterar o código de resposta para um
      # status, caso contrário, os erros não serão exibidos
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  # private - Faz com que todos os métodos abaixo da sua declaração se tornem
  # executáveis apenas dentro da classe
  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Redireciona para lista de artigos quando o usuário estiver logado e acessar o caminho raiz
    # redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to root_url
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, only: [ :edit, :update ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
    <p><strong>Title:</strong> <%= article.title %></p>
    <p><strong>Description:</strong> <%= truncate(article.description, length: 100) %> </p>

    <p>
        <small>
            Created
            <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <br />
            Created <%= time_ago_in_words(article.created_at).capitalize %> ago, edited <%= time_ago_in_words(article.updated_at).capitalize %> ago
        </small>
    </p>

    <%= link_to 'Show', article_path(article) %>
    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        | <%= link_to 'Edit', edit_article_path(article) %> |
        <%= link_to 'Delete', article, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<%# Utilize data: { turbo: false } para conseguir renderizar algo na tela com 
o render, ou qualquer outra forma de renderizar algo dentro da atual, assim que 
a ação de submissão de formulário for feita %>

<%# <%= form_with(model: @article, local: true, data: { turbo: false}) do |f| %>

<%= form_with(model: @article, local: true, data: { turbo: false}) do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br />
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit a article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<%= will_paginate @articles, :container => false %>

<%= render 'article' %>

<br /><br />

<%= will_paginate @articles, :container => false %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<p>
    <%= link_to 'Return to articles listing', articles_path %>
</p>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title:</strong> <%= @article.title %></p>
<p><strong>Description:</strong> <%= @article.description %> </p>

<p>
    <small>
        Created 
        <% if @article.user %>
            by <%= link_to @article.user.username, user_path(@article.user) %>
        <% end %>
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <br />
        Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago
    </small>
</p>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home page', root_path %> |
<%= link_to 'About page', about_path %> |
<%= link_to 'Bloggers', users_path %> |
<%= link_to 'Articles listing', articles_path %> |
<% if logged_in? %>
    <%= link_to 'Create new article', new_article_path %> |
    <%= "(Admin)" if current_user.admin? %>
    <%= link_to current_user.username, user_path(current_user) %> |
    <%= link_to 'Log out', logout_path, data: { turbo_method: :delete } %> |
    <%= link_to 'Delete account', user_path(current_user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% else %>
    <%= link_to 'Log in', login_path %> |
    <%= link_to 'Sign up', signup_path %> 
<% end %>

<br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Em layouts é necessário importar os partials com o diretório no
    caminho %>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <h1>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h1>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true, data: { turbo: false }) do |f| %>
    <p>
        <%= f.label :username %><br />
        <%= f.text_field :username %>
    </p>
    <p>
        <%= f.label :email %><br />
        <%= f.email_field :email %>
    </p>
    <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account') %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Alpha Bloggers</h1>

<%= will_paginate @users, :container => false %>

<% @users.each do |user| %>
    <h2>
        <%= link_to gravatar_for(user, size: 100), user_path(user) %>
        <%= link_to user.username, user_path(user) %>
    </h2>

    <p>
        <small>
            Joined <%= time_ago_in_words(user.created_at) %>
        </small>
    </p>
    
    <%= link_to 'View profile', user_path(user) %>
    <% if logged_in? %>
        <% if user == current_user %>
            | <%= link_to 'Edit profile', edit_user_path(user) %>
        <% end %>
        <% if current_user.admin? %>
            | <%= link_to 'Delete user', user_path(user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete the user account and all associated articles?' } %>
        <% end %>
    <% end %>
<% end %>

<br /><br />

<%= will_paginate @users, :container => false %>

app/views/users/new.html.erb
<h1>Sign up to Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= gravatar_for @user, size: 100 %> <%= @user.username %>'s profile</h1>

<p>
    <%if logged_in? && @user == current_user %>
        <%= link_to "Edit your profile", edit_user_path(@user) %>
    <% end %>
</p>

<%= will_paginate @articles, :container => false %>

<%= render 'articles/article' %>

<%= will_paginate @articles, :container => false %>